volumes:
  files-datavolume-app:

networks:
  gcp_network:
    name: ${DOCKER_NETWORK}
    driver: bridge
    external: true

services:
  app.fe.customer:
    labels:
      svc: "app-fe-customer"
    restart: always
    container_name: app.fe.customer
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      APP_PORT: 3000
    ports:
      - 3000
    networks:
      - gcp_network